### ISSUE TITLE
2018 컨퍼런스 테마 선정

### ISSUE THREAD

**Issue by 2woongjae** [seouljs/seoul.js.org#11]
1차 후보 테마
- Rainbow JavaScript
- JavaScript Everywhere
- *.js
- Colorful JavaScript
- 웹의 수도 : 서울JS

아래 댓글로 여러가지 드립 기대합니다.

**Comment by rhiokim** [comment]
드립 하나 하고 가요 =3=3=3
- Universal Javascript 
  - https://medium.com/@mjackson/universal-javascript-4761051b7ae9
  - https://github.com/facebook/react/pull/4041

**Comment by Alchemist85K** [comment]
여러가지 이유로 사용 못할 가능성이 있지만,,,

- You Don't Know
  - http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=112387204
- You know nothing 
  - https://www.google.co.kr/search?q=You+know+nothing&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjGweinpJzXAhXDzbwKHaABBacQ_AUICigB&biw=1568&bih=893#imgrc=F2cS4nr5xdy7oM:

**Comment by ragingwind** [comment]
Everywhere/온누리/온갖 Javascript

> 브라우저뿐 아니라 아주 많은 분야에서 적용되는 Javascript 에 대해서 다룬다

**Comment by byungjune** [comment]
- Hello Javascript
- Let's Javascript
- Javascript World
- Evolution of Javascript
- Javascript Revolution

**Comment by bomho** [comment]
JigJag : 온갖 자바스크립트의 연결

**Comment by ragingwind** [comment]
일단 닫습니다.
