### ISSUE TITLE
2018 컨퍼런스 장소 후보지

### ISSUE THREAD

**Issue by 2woongjae** [seouljs/seoul.js.org#12]
후보지를 밑에 댓글로 달아주세요~~!
없는건 무조건 달아주세요 :)

**Comment by 2woongjae** [comment]
삼성SDS / 구체적인 최대 인원 조사 중

**Comment by 2woongjae** [comment]
광화문 마이크로소프트

**Comment by 2woongjae** [comment]
세종대학교

**Comment by 2woongjae** [comment]
양재 엘타워

**Comment by 2woongjae** [comment]
상암 누리꿈 스퀘어

**Comment by Alchemist85K** [comment]
코엑스 Hall E + 컨퍼런스 룸(남) 3F
http://www.coex.co.kr/facility-lease/conference/facilities-information

**Comment by ragingwind** [comment]
저의 의사를 이모지로 달아보았습니다

**Comment by ragingwind** [comment]
일단 닫습니다.
