### ISSUE TITLE
2018 Happy New Year :tada:

### ISSUE THREAD

**Issue by rhiokim** [seouljs/seoul.js.org#13]
2018 Happy New Year :tada:

- [ ] 2018 신년회
- [ ] 2018 Seoul.js 계획

---

- [ ] @ragingwind @2woongjae @rhiokim 각자 이모저모 (세상돌아가는... 이야기)
- [ ] 컨퍼런스 이모저모 (마크 부탁해요 ^^)
- [ ] 1Q 끝나기전에 뭐하나 할까요?
  - [ ] 온라인으로 5~10 정도 모여서 자기 자랑?
     - 예를 들어 next.js 5 로 boilerplate 만들고 있어요. next.js 용 플러그인 만들어봤어요... 요런 요런 기술 썼구요. 써보니 소감은 이래저래요.  
     - Webpack 4 써봤는데 ts-loader 관련 이슈가 있었는데 이래 해결했어요.  
     - hyperapp 이랑 parcel 요즘 이슈길레 써봤는데 이래서 저래서 괜찮네요.

**Comment by ragingwind** [comment]
Let's get it

**Comment by ragingwind** [comment]
미팅결과 공유합니다.

온라인 대형 컨퍼런스 (OMC)
- 상용 플랫폼을 사용하여 온라인 컨퍼런스를 정기적으로 진행 해보자. 기본적인 입장료와 특정 플랫폼 가입 유도 필요
- 기본적인 토크 형태는 라이트닝 포맷이며 핫하고 자극적인 주제, 라이브
- 별도의 팀을 조직해서 감독과 스탭 으로 구성한다.
- 정기적 월간 형태로 진행
- 200 명 규모
