### ISSUE TITLE
JS News Room

### ISSUE THREAD

**Issue by rhiokim** [seouljs/seoul.js.org#22]
# JS Coffee Break

매일 매일 발생하는 JS 관련 이슈들(릴리즈 소식, 미디엄 아티클, 트윗)을 그날 그날 만나서 정해진 시간에 Seoul.js 디스코드 채널(https://discord.gg/jagUyv7) 에서 1~3 개의 주제에 대해 이야기하고 놀기

## 장소 및 일정

언제, 어디서나 in Seoul.js 디스코드 채널

* 일시: Daily
* 시간: 오후 10:00 - 11:00
* 장소: https://discord.gg/jagUyv7

## 행사 스케쥴

정해지지 않는 시간동안 자유롭게 Javascript 관련된 이야기

1. 미팅 이틀전에 이야기꺼리를 투척한다. (어디에 투척?)
2. 디스코드 음성채널에 만나서 이야기 나눈다. (녹음도 한다?)

## 대상

이야기를 나누고 싶은 주제가 있거나 관심있는 주제가 있다면 누구나 (일단은 제한된 인원수 -8명 정도- 로 진행해보면서) 

## 참여방법

디스코드로 그냥 조인

## 스태프

아직없음

## 후원

아직없음

## CoC

모든 Seoul.js 의 이벤트는 [Code of Conduct](https://seoul.js.org/seoul.js/code-of-conduct.html) 를 따릅니다.

**Comment by ragingwind** [comment]
- 데일리 보다는 주간은?
- spectrum or github 를 통해서 모아보는건가요?

**Comment by rhiokim** [comment]
그냥 우리 커뮤니티에 사람들이 많은데 그 분들이 매일 보는 다양한 정보들을 그냥 우리 커피타임처럼 그냥 매우 가볍게 준비없이 디스코드에서 만나서 이야기같은걸 하는 정도로만 상상해봤어요.

그리고 향후에는 운영진 없이도 여러 음성채널에서 2,3 개의 주제를 갖은 사람들이 모여서 (8명 남짓) 서로 이야기하고 기술 네트워킹하는 모습을 그려봅니다. ^^

주간은 데일리에서 나온 이야기를 주간에 더 심도있게 이야기해보면(요건 진짜 녹음해서 퍼블리싱도 하고 ^^) 좋을것 같네요.

처음에는 그냥 참여할때 그 자리에서 투척하는 방식을 생각하고 있습니다.

일단 트라이 해볼께요.

**Comment by rhiokim** [comment]
1st
* @rhiokim - https://www.youtube.com/watch?v=XYAgmj527PU&t=901s

2st
* @rhiokim - https://www.npmjs.com/package/node-mac
* @j2p - [deno 0.3.9 and 0.3.10 release notes review](https://github.com/denoland/deno/releases/tag/v0.3.9)

**Comment by rhiokim** [comment]
# node-mac

시스템 이벤트 혹은 어떤 맥 애플리케이션에서 발생하는 이벤트를 node.js 에서 인지할 수 있을까? 를 고민하다 써칭하던 중

node-mac 은 plist 를 생성하고 그 값을 launchctl 실행하면서 인자로 넘겨줌

여기서 plist 는 등록할 서비스의 정의와 실행 시 필요한 설정들을 XML 로 담고 있음
그리고 launchctl 은 mac 에서 제공하는 서비스 관리를 위한 CLI 

mac case
* launchctl launchd - https://en.wikipedia.org/wiki/Launchd 

window case
* runas - https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc771525(v%3Dws.11)

linux case
* systemctl 은 systemd 시스템 메니저를 제어하는 CLI
* https://ko.wikipedia.org/wiki/Systemd

## 기타

* 애플 직원이 만든 https://www.launchd.info/
>  "a unified, open-source service management framework for starting, stopping and managing daemons, applications, processes, and scripts. Written and designed by Dave Zarzycki at Apple, it was introduced with Mac OS X Tiger and is licensed under the Apache License."

**Comment by rhiokim** [comment]
3rd coffee break 05.10 9PM
* @j2p Deno 0.4.0 release note review
* @rhio Rust Web Developer Roadmap overview
* @jimmymoon  Next.js + AMP demo

**Comment by rhiokim** [comment]
3번 진행해본 결과

* 스피커 3명정도면 적당, 주제가 짧아도 이야기 하다보면 20분은 쉽게 넒어감
* 이야기거리는 많으면 많을 수록 좋을 것 같고 2,3명으로 진행할 경우 부제 시 원활한 진행이 어려움
* 듣는 사람도 좀더 많으면 좋을듯 북적북적하게 하는게 좋을 듯

**Comment by ragingwind** [comment]
이건 클로즈 하고 이제 매주 이슈 발행하는건 어떨까요? @rhiokim

**Comment by rhiokim** [comment]
넵!
