### ISSUE TITLE
Deno Meetup #1

### ISSUE THREAD

**Issue by ragingwind** [seouljs/seoul.js.org#23]
# Deno Meetup #1

Deno 1.0 릴리즈에 맞추어 Deno 의 전반적인 내용을 소개하는 미트업. 트위치 플랫폼을 이용해서 송출합니다.

- [ ] 날짜, 시간 확정
- [ ] 스웩! 스티커
- [ ] 프로그램 선정
- [ ] 스피커 모집
- [ ] 안내 페이지
- [ ] 후원

## 장소 및 일정

* 일시, 시간: 미정
* 장소: https://www.twitch.tv/seouljs/

## 대상

Deno 에 관심있는 누구든

## 참여방법

트위치 로그인

## 스태프

호스트와 진행: @ragingwind 

## CoC

모든 Seoul.js 의 이벤트는 [Code of Conduct](https://seoul.js.org/seoul.js/code-of-conduct.html) 를 따릅니다.

**Comment by ragingwind** [comment]
주제는 생각나는건 (이후에 깃헙(seouljs)에 이슈잉 할게요) 3세션으로 30 분정도의 오버뷰 내용이면 스타팅으로 굿일 것 같아요

- 1.0 features and basic use cases (cli, hello world, importing, ts)
- adv, internal architecture, (rust, tokio, ...)
- simple http server
- more (추가 환영)

**Comment by ragingwind** [comment]
주제를 먼저 다듬어야 할 것 같아요. 세가지 정도, 기본 내용, 30분 이내 정도면 좋을 것 같습니다.

**Comment by Rokt33r** [comment]
deno 외부 모듈 배포가 어떻게 되는지 알고 싶어요! `importing` 에 포함되려나요?

**Comment by ragingwind** [comment]
@Rokt33r 두가지 측면이 있을 것 같네요. 단순히 사용하는 부분이면 개론 정도에서 그게 아니고 `외부 모듈 제작 배포` 을 포함해서 npm 에 릴리즈 하는 방법 처럼 분리 될 수도 있을 것 같아요. 하나 분리해서 짧게 소개해도 좋겠네요.

**Comment by rhiokim** [comment]
* intro. standard modules (web standard apis, websocket)
> standard libs 에 대해서 간단하게 리뷰하면서 
> deno 에서 web standards 를 어떻게 녹이고 있는 지

deno.land 있는 컨텐츠들도 좀 소개할 만한게 좀 있는거 같네요.
* registry (요건 @Rokt33r 아이디어에 묻어서 소개해도 될듯)
* benchimark (그래프의 의미를 좀 알려주면 좋을것 같은)

**Comment by ragingwind** [comment]
0.10.0 이 나와서 부제는 `Deno 의 탄생기` 로. /cc @2woongjae
