### ISSUE TITLE
JSConf EU 2019 리뷰

### ISSUE THREAD

**Issue by ragingwind** [seouljs/seoul.js.org#24]
# 이벤트 타이틀

## 장소 및 일정

* 일시: 2019년 06월 20일 목요일
* 시간: 오후 09:00
* 장소: https://www.twitch.tv/seouljs/

## 행사 스케쥴

| 시간 | 스케쥴 |
|-----------|----|
| 21:00 - 21:20 | TBD |
| 21:20 - 21:40 | TBD |
| 21:40 - 21:50 | 휴식 |
| 21:50 - 22:10 | TBD |
| 22:10 - 22:30 | TBD |

## 대상

JS 소식에 관심 있는 모든 사람

## 참여방법

트위치 접속

## 스태프

@ragingwind @rhiokim 

이벤트를 개최하기 위해 도움 및 기여해 주신 분들입니다.

## CoC

모든 Seoul.js 의 이벤트는 [Code of Conduct](https://seoul.js.org/seoul.js/code-of-conduct.html) 를 따릅니다.

**Comment by rhiokim** [comment]
굳굳,
