### ISSUE TITLE
meeting notes (2017-07-18)

### ISSUE THREAD

**Issue by rhiokim** [seouljs/seoul.js.org#4]
## 킥오프 미팅전 다룰 내용

1. 발표 컨텐츠 등록 기준
    1.1 컨텐츠 수준 (not strict)
        - 누가가 정해지면 누가의 판단에 의해 자유롭게 하도록 하는게 좋을것 같기도 해요
    1.2 누가 등록
        - 커미티까지, 아니면 애니바디?
    1.3 언제 등록
        - 행사날이 8월 1일이면 due date 를 미리 정하고 그 기간에 맞춰 하는 방식일까요?
2. 발표 컨텐츠 선정 기준
    2.2 행사의 컨셉이 중요할듯 (strict)
        - 같은 Seoul.js 컨퍼런스여도, 테마가 생길것 같죠??
    2.3 누가 선정
        - 투표를 하기로 했죵?? 누가 투표?? 커미티??, 애니바디??
    2.4 언제 선정
        -  마찬가지로 행사날이 8월 1일이면 due date 를 미리 정하고 그 기간에 맞춰 하는 방식일까요?
3. 스피커 선정 기준
    3.1 어떤 기준 (very strong strict)
        - 예) 발표 경험 몇번?, 저자?, 오픈소스 컨트리뷰터? 같은... 이건 막쓴거
    3.2 누가 선정
    3.3 언제 선정
4. 발표 컨텐츠 라벨링
5. 커미티 역할
    - 자신이 무엇을 해야하는지 아직은 감을 못잡는 상황이라 구체적인 역할을 줘야 하지 않을까?
6.  커미티 혜택
7. '님' 호칭 결정
    - 영어 이름?
    - 닉네임으로?
    - 한글 이름은 님자 해야지 않을까?
8. 언제라는 키워드때문에 Seoul.js 의 연간 계획이 나와야 하지 않을까?

## 8.18 밋업 관련
a. 발표 컨텐츠 픽스
    - 4번째 발표 건에 대하여...
b. 발표 컨텐츠 업데이트
c. BI 진행 상황 공유
d. 촬영 및 음성 녹음 관련

**Comment by ragingwind** [comment]
> 제가 의견 달기 쉽게 번호/알파벳으로 라벨링 했습니다.

1. 이슈(토픽)을 등록은 쉬운데 확정은 리뷰단계를 거치면 될 것 같습니다. 리뷰 단계에서. 좋은 주제지만. 발룬티어나 적당한 스피커등이 없다고 판단되거나, 내용이 부족한 경우 리젝, 또는 업데이트하는 과정을 오거나이저/커미티가 도와주도록 하면 될 것 같습니다.
1.3 오거나이저/커미티 프로그램 기획/컨셉 확정 -> 기존 아이템에서 추천자료 몇개 선정 -> 기한 알림 -> 추가등록 과정이면 되지 않을까요? 먼저 프로그램 기획을 하고 관련해서 토픽을 먼저 어느정도 선정해 놓고 부족분이나 또는 굉장히 좋은 아이템이 있으면 먼저 선정된 프로그램에서 제외 하는 것도.
2. 앞에서 이야기 한것 처럼 프로그램 기획을 오거나이저/커미티, 외부투표후에 내부정리 수순(상황과 프로그램 컨셉에 맞는)이 맞을 것 같은데요.
3. 명확한 규정이 있으면 좋은데 유연했으면 합니다. 간단하게 리밋은 정하고 점차 다듬어 나가면?. 먼저 스피커가 가능한 분들을  awesome-js-developer 저희가 등록하거나 (문의후?) 스스로 합당 하다고 하면 커밋을 받는 것(Call for Commit) 기준으로 했으면 좋겠어요. > 뉴비들이 멘토로 삼기에 적당한 정보를 제공하는 용도와 스피커 섭외에 사용
4. 러프하게만 규칙을 잡고 필요에 따라 수정/업데이트 하는 걸로. 이거는 제가 정리해서 따로 문서로 뺄께요
5/6. 저희와 같이 프로그램 기획과 컨퍼런스 진행의 경험이 제일 큰 베네핏 같은데요
7. 저는 이견없습니다. 한글이름을 영어 아이디로 생각하면?
8. 네 어느정도 확정해야 하고 페이지등 작업을 해야 할 것 같습니다. 예를 들면 11 월이면 지금 작업 시하는게 딱일 것 같아요.

- a. ?
- b. done
- d. 화면을 리모트에서 캡처하고 소리는 핸드폰으로 녹음한다음 합쳐서 업로드 하면 어떨까요? (제가하는 방식)

**Comment by ragingwind** [comment]
라벨링은 https://github.com/seouljs/seoul.js.org/issues/5 에 다시 정리했습니다. 업데이트 하기 쉽게 테이블은 ...

**Comment by 2woongjae** [comment]
## 킥오프 미팅전 다룰 내용

1. 발표 컨텐츠 등록 기준
    1.1 컨텐츠 수준
        - not strict
        - 방향은 정해주고, 리뷰를 통해 정리해가는 과정
    1.2 누가 등록
        - 아무나
    1.3 언제 등록
        - 컨텐츠를 기준으로 가능하면 자주
    1.4 리뷰
        - 손을 대는 작업이 중요하다.
        - 커미티? 또는 오거나이저?
2. 발표 컨텐츠 선정 기준
    2.1 행사의 컨셉이 중요할듯 (strict)
        - 같은 Seoul.js 컨퍼런스여도, 테마가 생길것 같죠??
    2.2 누가 선정
        - 리스트업
            - 리뷰 & 행사 컨셉
            - 보팅으로 선정할 것인지
            - 상황에 맞춰 적절히 균형을 맞춘다.
    2.3 언제 선정
        -  마찬가지로 행사날이 8월 1일이면 due date 를 미리 정하고 그 기간에 맞춰 하는 방식일까요?
3. 스피커 선정 기준
    3.1 어떤 기준 (very strong strict)
        - 예) 발표 경험 몇번?, 저자?, 오픈소스 컨트리뷰터? 같은... 이건 막쓴거
    3.2 누가 선정
    3.3 언제 선정
4. 발표 컨텐츠 라벨링
5. 커미티 역할
    - 자신이 무엇을 해야하는지 아직은 감을 못잡는 상황이라 구체적인 역할을 줘야 하지 않을까?
6. 커미티 혜택
7. '님' 호칭 결정
    - 영어 이름?
    - 닉네임으로?
    - 한글 이름은 님자 해야지 않을까?
8. 언제라는 키워드때문에 Seoul.js 의 연간 계획이 나와야 하지 않을까?

## 8.18 밋업 관련
a. 발표 컨텐츠 픽스
    - 4번째 발표 건에 대하여...
b. 발표 컨텐츠 업데이트
c. BI 진행 상황 공유
d. 촬영 및 음성 녹음 관련
    - 원본만 잘뜨면 영상 편집자 섭외
