### ISSUE TITLE
Labeling of Topics on Voting

### ISSUE THREAD

**Issue by ragingwind** [seouljs/seoul.js.org#5]
## Status of Contents

- wanted : 발표자가 지정되지 않은 이슈
- assigned: 발표 내용과 발표자가 지정된 이슈

## Categories of Contents

- mobile: 모바일 관련
- tooling: 생산성, 유용한 툴 활용법
- frameworks: 모던 프레임웍(React, Vue, Angular 등)
- node.js: Node.js 전반적인
- design: UI/UX 와 디자인 관점에서의 기술이나 경험
- standards: 브라우저 표준 기술(HTML, CSS, JS, Browser Tech)
- opensources: 모던 오픈 소스들의 활용 사례
- experiences: 직접 개발하거나 경험을 바탕으로 강한 인사이트를 줄 수 있는...
- desktop: 데스크탑 애플리케이션 기술
- iot: Internet Of Thing
- clouds: 서버 및 인프라 기술
- ai: 인공지능/머신러닝등과 연관된
- backends: Backends 관련된
- etc: 기타

**Comment by rhiokim** [comment]
여기에 나열된 내용들은 라벨링 완료하였습니다. 완료하셔도 될것 같아요.
