### ISSUE TITLE
Meeting repogitory 정리하기

### ISSUE THREAD

**Issue by ragingwind** [seouljs/seoul.js.org#8]
- [ ] 이름 변경: meeting -> meetings/milestones/1, meetings/issues/22
- [ ] issues 라벨 규칙 업데이트: https://github.com/seouljs/meeting/labels

**Comment by ragingwind** [comment]
- 라벨 규칙 업데이트가 좀 필요해보입니다. 좀 길더라도 . 보다는 prefix 붙이는게 가독성이 좋아 보여요
- cate-frameworks|iot|mobile
- 디텔일한 라벨 react|angular 제거, 제목에서 이미 노출 되거나 오버워크일 가능성
- status 는 그대로 좋고 계속 추가 하면 될 것 같아요

**Comment by rhiokim** [comment]
. 은 단순히 해당 라벨이 라벨들중에 가장 앞에 표시되게 하려는 의도였는데...
돈드는 것도 아닌데 ㅋ 적용하시면 팔로우 할께요..

**Comment by ragingwind** [comment]
이거 미팅에 있는거 일단 모두 클로즈 하고, 이번 OMC 에서 다시 하는건 어떠세요.

**Comment by ragingwind** [comment]
리포지토리를 일단 닫을게요.
